# Generated by Django 2.2.5 on 2019-09-16 10:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=20, null=True)),
                ('coin_image', models.ImageField(blank=True, null=True, upload_to='solo/coin')),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_type', models.CharField(choices=[('1', 'solo'), ('2', 'group'), ('3', 'multiplayer')], max_length=50)),
                ('max_number_of_players', models.PositiveIntegerField(default=2)),
                ('max_rounds', models.PositiveIntegerField(default=3)),
                ('max_play_time', models.PositiveIntegerField(default=30)),
                ('max_resume_time', models.PositiveIntegerField(default=120)),
            ],
        ),
        migrations.CreateModel(
            name='Hand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=20, null=True)),
                ('hand_image', models.ImageField(blank=True, null=True, upload_to='solo/hand')),
            ],
        ),
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.PositiveIntegerField(default=0)),
                ('max_points', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_points', models.PositiveIntegerField(default=0)),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pl_level', to='solo.Level')),
                ('ruser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pl_ruser', to='registration.RegisteredUser')),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='r_game', to='solo.Game')),
            ],
        ),
        migrations.CreateModel(
            name='Round',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prediction', models.PositiveIntegerField(default=0)),
                ('actual', models.PositiveIntegerField(default=0)),
                ('round_point', models.PositiveIntegerField(default=0)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ro_player', to='solo.Player')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ro_room', to='solo.Room')),
                ('round_winner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ro_round_winner', to='solo.Player')),
            ],
        ),
        migrations.CreateModel(
            name='RoomManager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_online', models.BooleanField(default=False)),
                ('inactive_duration', models.PositiveIntegerField(default=0)),
                ('total_game_points', models.PositiveIntegerField(default=0)),
                ('coin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rm_coin', to='solo.Coin')),
                ('hand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rm_hand', to='solo.Hand')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rm_player', to='solo.Player')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rm_room', to='solo.Room')),
            ],
        ),
        migrations.AddField(
            model_name='room',
            name='players',
            field=models.ManyToManyField(related_name='room_player', through='solo.RoomManager', to='solo.Player'),
        ),
        migrations.AddField(
            model_name='room',
            name='started_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='r_started_by', to='solo.Player'),
        ),
        migrations.AddField(
            model_name='room',
            name='winner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='r_room_winner', to='solo.Player'),
        ),
    ]
