# Generated by Django 2.2.5 on 2019-09-17 06:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('solo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roommanager',
            name='inactive_duration',
        ),
        migrations.RemoveField(
            model_name='roommanager',
            name='is_online',
        ),
    ]
