# Generated by Django 2.2.5 on 2019-09-18 10:00

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0004_auto_20190917_1307'),
        ('solo', '0002_auto_20190917_0628'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserOnlineStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_online', models.PositiveIntegerField(default=0)),
                ('exit_time', models.DateTimeField(default=datetime.datetime.now)),
                ('offline_duration', models.PositiveIntegerField(default=0)),
                ('is_engaged', models.BooleanField(default=False)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='os_room', to='solo.Room')),
                ('ruser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='os_ruser', to='registration.RegisteredUser')),
            ],
        ),
    ]
