# Generated by Django 2.2.5 on 2019-09-19 05:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('solo', '0003_useronlinestatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='roommanager',
            name='inactive_duration',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='roommanager',
            name='is_online',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='room',
            name='players',
            field=models.ManyToManyField(related_name='room_players', through='solo.RoomManager', to='registration.RegisteredUser'),
        ),
        migrations.AlterField(
            model_name='room',
            name='started_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='r_started_by', to='registration.RegisteredUser'),
        ),
        migrations.AlterField(
            model_name='room',
            name='winner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='r_room_winner', to='registration.RegisteredUser'),
        ),
        migrations.AlterField(
            model_name='roommanager',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rm_player', to='registration.RegisteredUser'),
        ),
        migrations.AlterField(
            model_name='round',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ro_player', to='registration.RegisteredUser'),
        ),
        migrations.AlterField(
            model_name='round',
            name='round_winner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ro_round_winner', to='registration.RegisteredUser'),
        ),
    ]
