# Generated by Django 2.2.5 on 2019-09-19 06:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('solo', '0004_auto_20190919_0558'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useronlinestatus',
            name='room',
        ),
        migrations.RemoveField(
            model_name='useronlinestatus',
            name='ruser',
        ),
        migrations.DeleteModel(
            name='Player',
        ),
        migrations.DeleteModel(
            name='UserOnlineStatus',
        ),
    ]
