# Generated by Django 2.2.5 on 2019-09-19 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('solo', '0005_auto_20190919_0600'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Level',
        ),
    ]
