# Generated by Django 2.2.5 on 2019-09-19 07:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('solo', '0006_delete_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roommanager',
            name='coin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rm_coin', to='solo.Coin'),
        ),
        migrations.AlterField(
            model_name='roommanager',
            name='hand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rm_hand', to='solo.Hand'),
        ),
    ]
