# Generated by Django 2.2.5 on 2019-09-19 08:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('solo', '0007_auto_20190919_0731'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='winner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='r_room_winner', to='registration.RegisteredUser'),
        ),
    ]
