# Generated by Django 2.2.5 on 2019-09-30 05:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0011_auto_20190930_0556'),
        ('solo', '0009_chatmessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('number_of_players', models.PositiveIntegerField(default=2)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gr_ruser', to='registration.RegisteredUser')),
            ],
        ),
        migrations.RemoveField(
            model_name='room',
            name='winner',
        ),
        migrations.RemoveField(
            model_name='round',
            name='round_winner',
        ),
        migrations.AddField(
            model_name='roommanager',
            name='is_game_winner',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='round',
            name='is_round_winner',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='GroupJoinedMembers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joined_on', models.DateTimeField(auto_now_add=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gm_group', to='solo.Group')),
                ('ruser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gm_ruser', to='registration.RegisteredUser')),
            ],
        ),
    ]
