# Generated by Django 2.2.5 on 2019-11-13 13:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('solo', '0010_auto_20190930_0556'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='started_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='r_started_by', to='registration.RegisteredUser'),
        ),
    ]
