# Generated by Django 2.2.5 on 2019-11-16 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solo', '0011_auto_20191113_1341'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='unity_room_id',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
