# Generated by Django 2.2.5 on 2019-11-20 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('solo', '0012_room_unity_room_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='unity_room_id',
            new_name='socket_room_id',
        ),
    ]
