# Generated by Django 2.2.5 on 2020-06-05 06:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0022_registereduser_profile_image_file'),
        ('solo', '0014_auto_20200430_1024'),
    ]

    operations = [
        migrations.CreateModel(
            name='GamePlayerManager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_game_point', models.PositiveIntegerField(default=0)),
                ('is_game_winner', models.BooleanField(default=False)),
                ('coin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gpm_coin', to='solo.Coin')),
            ],
        ),
        migrations.RemoveField(
            model_name='roommanager',
            name='coin',
        ),
        migrations.RemoveField(
            model_name='roommanager',
            name='hand',
        ),
        migrations.RemoveField(
            model_name='roommanager',
            name='player',
        ),
        migrations.RemoveField(
            model_name='roommanager',
            name='room',
        ),
        migrations.RemoveField(
            model_name='round',
            name='room',
        ),
        migrations.AddField(
            model_name='game',
            name='room',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='round',
            name='game',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ro_game', to='solo.Game'),
        ),
        migrations.AddField(
            model_name='round',
            name='round_number',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='room',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.DeleteModel(
            name='Room',
        ),
        migrations.DeleteModel(
            name='RoomManager',
        ),
        migrations.AddField(
            model_name='gameplayermanager',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gpm_game', to='solo.Game'),
        ),
        migrations.AddField(
            model_name='gameplayermanager',
            name='hand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gpm_hand', to='solo.Hand'),
        ),
        migrations.AddField(
            model_name='gameplayermanager',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gpm_player', to='registration.RegisteredUser'),
        ),
        migrations.AddField(
            model_name='game',
            name='players',
            field=models.ManyToManyField(related_name='game_players', through='solo.GamePlayerManager', to='registration.RegisteredUser'),
        ),
    ]
