# Generated by Django 2.2.5 on 2020-06-05 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solo', '0015_auto_20200605_0617'),
    ]

    operations = [
        migrations.AddField(
            model_name='round',
            name='room',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
