# Generated by Django 2.2.5 on 2020-06-05 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solo', '0016_round_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='gameplayermanager',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='round',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
