# Generated by Django 2.2.5 on 2019-09-17 09:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_auto_20190917_0628'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(blank=True, max_length=1000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserContactList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('contact_country_code', models.CharField(blank=True, max_length=10, null=True)),
                ('contact_mobile', models.CharField(blank=True, max_length=15, null=True)),
                ('contact_status', models.CharField(choices=[('1', 'Saved'), ('2', 'Invited'), ('3', 'Installed')], max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ucl_ruser', to='registration.RegisteredUser')),
            ],
        ),
    ]
