# Generated by Django 2.2.5 on 2019-09-17 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0003_applink_usercontactlist'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registereduser',
            old_name='inactive_from',
            new_name='exit_time',
        ),
        migrations.AddField(
            model_name='registereduser',
            name='offline_duration',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
