# Generated by Django 2.2.5 on 2019-09-19 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0005_countrycode'),
    ]

    operations = [
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.PositiveIntegerField(default=0)),
                ('max_points', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.RenameField(
            model_name='registereduser',
            old_name='offline_duration',
            new_name='total_points',
        ),
        migrations.RemoveField(
            model_name='registereduser',
            name='exit_time',
        ),
        migrations.AddField(
            model_name='registereduser',
            name='level',
            field=models.CharField(default='', max_length=2),
        ),
    ]
