# Generated by Django 2.2.5 on 2019-09-20 08:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0008_auto_20190919_0648'),
    ]

    operations = [
        migrations.AddField(
            model_name='countrycode',
            name='country',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='registereduser',
            name='nationality',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rcountrycode', to='registration.CountryCode'),
        ),
        migrations.DeleteModel(
            name='Nationality',
        ),
    ]
