# Generated by Django 2.2.5 on 2019-09-20 08:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0009_auto_20190920_0846'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registereduser',
            name='nationality',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rnationality', to='registration.CountryCode'),
        ),
    ]
