# Generated by Django 2.2.5 on 2020-04-30 09:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0013_auto_20200430_0909'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserFriendList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('1', 'waiting'), ('2', 'accepted'), ('3', 'declined'), ('4', '')], default='1', max_length=50)),
                ('created_on', models.DateTimeField(auto_now=True)),
                ('friend', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='f_friend', to='registration.RegisteredUser')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='f_user', to='registration.RegisteredUser')),
            ],
        ),
    ]
