# Generated by Django 2.2.5 on 2020-04-30 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0016_gamerequestlist_group_groupjoinedmembers'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gamerequestlist',
            old_name='friend',
            new_name='nfrom',
        ),
        migrations.RenameField(
            model_name='gamerequestlist',
            old_name='player',
            new_name='nto',
        ),
    ]
