# Generated by Django 2.2.5 on 2020-04-30 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0017_auto_20200430_1044'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gamerequestlist',
            old_name='nfrom',
            new_name='grfrom',
        ),
        migrations.RenameField(
            model_name='gamerequestlist',
            old_name='nto',
            new_name='grto',
        ),
        migrations.AlterField(
            model_name='usernotification',
            name='req_type',
            field=models.CharField(choices=[('1', 'game request'), ('2', 'join group request'), ('3', 'other'), ('4', 'friend request'), ('5', 'from admin')], default='1', max_length=50),
        ),
    ]
