# Generated by Django 2.2.5 on 2020-04-30 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0018_auto_20200430_1115'),
    ]

    operations = [
        migrations.AddField(
            model_name='registereduser',
            name='share_code',
            field=models.CharField(default='', max_length=10),
        ),
    ]
