# Generated by Django 2.2.5 on 2020-05-26 15:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0019_registereduser_share_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupjoinedmembers',
            name='reference',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gm1_reference', to='registration.RegisteredUser'),
        ),
        migrations.AlterField(
            model_name='group',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gr1_ruser', to='registration.RegisteredUser'),
        ),
        migrations.AlterField(
            model_name='groupjoinedmembers',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gm1_group', to='registration.Group'),
        ),
        migrations.AlterField(
            model_name='groupjoinedmembers',
            name='ruser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gm1_ruser', to='registration.RegisteredUser'),
        ),
        migrations.AlterField(
            model_name='userfriendlist',
            name='friend',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='f_friend', to='registration.RegisteredUser'),
        ),
        migrations.AlterField(
            model_name='userfriendlist',
            name='player',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='f_user', to='registration.RegisteredUser'),
        ),
    ]
