# Generated by Django 2.2.5 on 2020-05-26 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0020_auto_20200526_1520'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groupjoinedmembers',
            name='reference',
        ),
    ]
