# Generated by Django 2.2.5 on 2020-06-03 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0021_remove_groupjoinedmembers_reference'),
    ]

    operations = [
        migrations.AddField(
            model_name='registereduser',
            name='profile_image_file',
            field=models.ImageField(blank=True, null=True, upload_to='user/profile_image'),
        ),
    ]
