# Generated by Django 2.2.5 on 2020-01-02 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TemporaryStorage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_name', models.CharField(default='', max_length=500)),
                ('room_pass', models.CharField(default='12345678', max_length=100)),
            ],
        ),
    ]
